version: '3'
services:
  odoo:
    image: odoo
    restart: always
    ports:
      - "8081:8069"
    links:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=mi-contraseña
    networks:
      - nw
    volumes:
      - addons:/mnt/extra-addons
      - config:/etc/odoo
      - data:/etc/lib/odoo
  db:
    image: postgres:9.4
    restart: always
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=mi-contraseña
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - nw
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
networks:
    nw:
volumes:
    data:
    addons:
    config:
    db-data: